#!/bin/sh
set -eu
pkg="${1:?package required}"
case "$pkg" in
  vlc|gimp|libreoffice|audacity|transmission-gtk) ;;
  *) exit 2 ;;
esac
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y "$pkg"
